// How to Input:
// import java.util.Scanner;
// Scanner scn = new Scanner(System.in);
// int num = scn.nextInt();
// scn.close();


// How to Type Cast:
// double a = 100;
// int b = (int) a;


// Trenery Operator:
// boolean b = (2 + num == 12) ? true : false;


// How to use Array:
// int arr[] = new int[10];
// for (int i = 0; i < arr.length; i++)

// How to use String:
// String str = "Azim";
// str.length()
// You can concanate string using '+' operator
// str.charAt(i) // For acess index
// Use: str.equals(str2) for compare

// 